source("analisis_bayesiano/00_funciones_bayes.R"); d<-leer_base_bayes()
pr <- c(prior(normal(0,.7),class="b"),prior(normal(-4,1.5),class="Intercept"))
spec <- list(
 BAYES_SENS_EDAD_CONTINUA=bf(MUERTE_FETAL_BINARIA~EDAD_Z+HIPERTENSIVOS_A+PAREJA_ESTABLE_A+INSTRUCCION_A+ACOMPANADA_BIN+CONTROLES_Z+SESIONES_Z+IVU_A),
 BAYES_SENS_EDAD_GESTACIONAL=bf(MUERTE_FETAL_BINARIA~EDAD_CAT+HIPERTENSIVOS_A+PAREJA_ESTABLE_A+INSTRUCCION_A+ACOMPANADA_BIN+CONTROLES_Z+SESIONES_Z+IVU_A+EG_Z),
 BAYES_CLINICO_INGRESO=bf(MUERTE_FETAL_BINARIA~EDAD_CAT+HIPERTENSIVOS_A+IVU_A+RIESGO_INGRESO_A+CONTROLES_Z),
 BAYES_OBSTETRICO=bf(MUERTE_FETAL_BINARIA~EDAD_CAT+HIPERTENSIVOS_A+RPM_A+DPP+HEMORRAGIA_A+VERTICE),
 BAYES_HIPERTENSION_AGRUPADA=bf(MUERTE_FETAL_BINARIA~EDAD_CAT+HIPERTENSIVOS_AGRUPADO+PAREJA_ESTABLE_A+INSTRUCCION_A+ACOMPANADA_BIN+CONTROLES_Z+SESIONES_Z+IVU_A),
 BAYES_SEGURO_SENSIBILIDAD=bf(MUERTE_FETAL_BINARIA~EDAD_CAT+SEGURO_A+INSTRUCCION_A+PAREJA_ESTABLE_A),
 BAYES_ACOMPANAMIENTO_DETALLE=bf(MUERTE_FETAL_BINARIA~EDAD_CAT+HIPERTENSIVOS_A+PAREJA_ESTABLE_A+INSTRUCCION_A+ACOMPANADA_DETALLE+CONTROLES_Z+SESIONES_Z+IVU_A))
fits <- lapply(names(spec),function(n) ajustar_modelo_bayes(spec[[n]],d,pr,n)); names(fits)<-names(spec)
outs <- c(BAYES_SENS_EDAD_CONTINUA="TABLA_BAYES_SENS_EDAD_CONTINUA.csv",BAYES_SENS_EDAD_GESTACIONAL="TABLA_SENS_CONTROLES_EG.csv",BAYES_CLINICO_INGRESO="TABLA_BAYES_CLINICO_INGRESO.csv",BAYES_OBSTETRICO="TABLA_BAYES_OBSTETRICO.csv",BAYES_HIPERTENSION_AGRUPADA="TABLA_SENS_HIPERTENSION_AGRUPADA.csv",BAYES_SEGURO_SENSIBILIDAD="TABLA_BAYES_SEGURO.csv",BAYES_ACOMPANAMIENTO_DETALLE="TABLA_BAYES_ACOMPANAMIENTO_DETALLE.csv")
tabs <- Map(function(f,n) guardar_tabla_modelo(f,n,outs[[n]]),fits,names(fits)); names(tabs)<-names(fits)
guardar_forest(tabs$BAYES_CLINICO_INGRESO,"FOREST_BAYES_CLINICO.png","Modelo clínico al ingreso")
guardar_forest(tabs$BAYES_OBSTETRICO,"FOREST_BAYES_OBSTETRICO.png","Modelo obstétrico")
for(n in c("BAYES_CLINICO_INGRESO","BAYES_OBSTETRICO","BAYES_SEGURO_SENSIBILIDAD")) guardar_ppc(fits[[n]],sub("BAYES_","",n))
principal<-readRDS(file.path(DIR_MODELOS,"BAYES_PRINCIPAL.rds"))
hip_orig<-resumen_posterior(principal,"Categorías originales")%>%filter(grepl("HIPERTENSIVOS",Parametro))
write_csv(bind_rows(hip_orig,tabs$BAYES_HIPERTENSION_AGRUPADA%>%filter(grepl("HIPERTENSIVOS",Parametro))),file.path(DIR_TABLAS,"TABLA_SENS_HIPERTENSION_AGRUPADA.csv"))
esc <- tabs$BAYES_SEGURO_SENSIBILIDAD %>% mutate(Porcentaje_perdido=100*(1-N_modelo/nrow(d)),Nota="Análisis de sensibilidad debido a elevada proporción de datos faltantes en la variable seguro.")
write_csv(esc,file.path(DIR_TABLAS,"TABLA_BAYES_SEGURO.csv"))
